image: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_20.04_workstation

run_tests:
  script:
    - export LC_ALL=C.UTF-8
    - export LC_LANG=C.UTF-8
    - pip install .
    - source $(pwd)/bin/fzirob_source.sh
    - fzirob get_checkout_base_dir
    - pytest-3 . -rA --cov robot_folders
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
