image: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_20.04_workstation

run_tests:
  script:
    - export LC_ALL=C.UTF-8
    - export LC_LANG=C.UTF-8
    - pip install .
    - source $(pwd)/bin/rob_folders_source.sh
    - fzirob get_checkout_base_dir
    - pytest-3 . -rA --cov
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

.build_matrix:
  parallel:
    matrix:
      # we use the ROS image since we want to try installing it later and need packages from the ROS
      # sources
      - CI_IMAGE: ros:foxy
      - CI_IMAGE: ros:humble

build_deb_pkg:
  parallel: !reference [.build_matrix, parallel]
  image: $CI_IMAGE
  script:
    - apt-get update && apt-get install -y dh-python python3-all fakeroot dpkg-dev debhelper
    - fakeroot dpkg-buildpackage -b
    - mkdir artifacts
    - cp ../python3-robot-folders*.deb artifacts/
    - apt-get install -y python3-vcstool python3-git python3-yaml python3-click
    - dpkg -i ../python3-robot-folders*.deb
    - source /usr/bin/rob_folders_source.sh
    - fzirob get_checkout_base_dir
  artifacts:
    paths:
      - artifacts/
