image: ids-git.fzi.de:5555/continuous_integration/ci_docker_images/ubuntu_20.04_workstation

run_tests:
  script:
    - export LC_ALL=C.UTF-8
    - export LC_LANG=C.UTF-8
    - pip install .
    - source $(pwd)/bin/rob_folders_source.sh
    - fzirob get_checkout_base_dir
    - pytest-3 . -rA --cov
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  needs: []

.build_matrix:
  parallel:
    matrix:
      # we use the ROS image since we want to try installing it later and need packages from the ROS
      # sources
      - CI_IMAGE: ros:humble

variables:
  DOCS_SOURCE: docs # The folder containing the sphinx conf.py file

include:
  - project: 'continuous_integration/ci_scripts'
    ref: master
    file: '/gitlab-ci-yml/doc_sphinx.yml'
