build: {
    generator: make,
    cmake_flags: "-DCMAKE_EXPORT_COMPILE_COMMANDS=1",
    make_threads: 4,
    install_ic: True,
    install_catkin: False,
    catkin_make_cmd: catkin_make,
    colcon_build_options: "--symlink-install"
}

repositories: {
    ic_workspace_grab_base_url: "git@ids-git.fzi.de:",
    ic_workspace_repo: "git@ids-git.fzi.de:core/ic_workspace.git",
    mca_workspace_repo: "git@ids-git.fzi.de:mca2/mca2.git"
}

directories: {
    # if left blank, the default robot_folders/checkout will be used
    checkout_dir: ,
    catkin_names: ["catkin_workspace", "catkin_ws"],
    colcon_names: ["colcon_workspace", "colcon_ws", "dev_ws"]
}
