build: {
    generator: make,
    cmake_flags: "-DCMAKE_EXPORT_COMPILE_COMMANDS=1",
    make_threads: 4,
    install_catkin: False,
    catkin_make_cmd: catkin_make,
    colcon_build_options: "--symlink-install"
}

directories: {
    # if left blank, the default ~/checkout will be used
    checkout_dir: ,
    catkin_names: ["catkin_workspace", "catkin_ws"],
    colcon_names: ["colcon_workspace", "colcon_ws", "dev_ws"],
    no_backup_dir: "~/no_backup"
}
